### ISSUE TITLE
Existing Content Checklist

### ISSUE THREAD

**Issue by RuudvH** [RuudvH/WP-FastStack#1]
Things to do related to content:
- [ ] Fix references and readmore links
- Not all references are sourced properly
- Add any extra readmore links
- Split reference and readmore?
- [ ] Fix code syntax
- Some code blocks have wrong highlighting

**Comment by RuudvH** [comment]
- [ ] Fix the left menu
- The auto-collapse can be very annoying
- [ ] Remove or add purpose to top menu
- Top menu is straight from template
- Do we need it?
- Maybe at progress for 'students'?
