### ISSUE TITLE
Wordpress Pages Checklist

### ISSUE THREAD

**Issue by RuudvH** [RuudvH/WP-FastStack#3]
# Deploy
## Mercury Vagrant (HGV)
- [ ] Add screenshots or output example from MySQL setup
- [ ] Add screenshots or output example from Ansible Playbook setup
- [ ] Add information to SWAP file and what has been setup by the playbook

## Easy Engine
- [ ] Clarify when to set passwords

# Optimization
- [ ] Install the WP Nginx Plugin + setup
- [ ] Install W3 Cache Plugin + setup
- Other Caching / Optmization?
- http://wpaxl.com/comprehensive-guide-on-setting-up-wordpress-on-a-linode-lemp-stack/
- https://rtcamp.com/wordpress-nginx/tutorials/single-site/fastcgi-cache-with-purging/
